version: "3.9"

services:
  maven:
    build: http://193.122.59.82:3000/petrovvitalik/Docker_Tomcat_Minimal/raw/master/Dockerfile-Maven
    volumes:
      - data-volume:/var/opt
    links:
      - tomcat
  tomcat:
    image: tomcat:10.0.5-jdk16-openjdk-slim-buster
    ports:
      - "8080:8080"
    volumes:
      - data-volume:/usr/local/tomcat/webapps/
volumes:
  data-volume: