version: "3.9"

services:
  maven:
    build: http://193.122.59.82:3000/petrovvitalik/Docker_Tomcat_Minimal/raw/master/Dockerfile-Maven
    volumes:
      - data-volume:/var/opt
    links:
      - tomcat
  tomcat:
    build:
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: /home/ubuntu/jdk-16
        target: /java
      - type: volume
        source: /home/ubuntu/apache-tomcat-9.0.45
        target: /tomcat
      - data-volume:/tomcat/webapps/
volumes:
  data-volume:
# data-volume:/usr/local/tomcat/webapps/