version: "3.9"

services:
  back:
    build: http://193.122.59.82:3000/petrovvitalik/Docker_Tomcat_Minimal/raw/master/Dockerfile-Maven
    volumes:
      - ./appdata:/var/opt
    links:
      - front
  front:
    build: http://193.122.59.82:3000/petrovvitalik/Docker_Tomcat_Minimal/raw/master/Dockerfile-Tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./appdata:/usr/local/tomcat/webapps/