version: "3.9"

services:
  maven:
    build: http://193.122.59.82:3000/petrovvitalik/Docker_Tomcat_Minimal/raw/master/Dockerfile-Maven
    volumes:
      - artifact-volume:/var/opt
      - java-volume:/java
      - tomcat-volume:/tomcat
    links:
      - tomcat
  tomcat:
    build: http://193.122.59.82:3000/petrovvitalik/Docker_Tomcat_Minimal/raw/master/Dockerfile-Tomcat
    ports:
      - "8080:8080"
    volumes:
      - artifact-volume:/tomcat/webapps/
      - java-volume:/java
      - tomcat-volume:/tomcat
volumes:
  artifact-volume:
  java-volume:
  tomcat:volume
# data-volume:/usr/local/tomcat/webapps/