version: "3.9"

services:
  maven:
    build: http://193.122.59.82:3000/petrovvitalik/Docker_Tomcat_Minimal/raw/master/Dockerfile-Maven
    volumes:
      - /home/ubuntu/DCMT_Shared:/var/opt
    links:
      - tomcat
  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/DCMT_Shared:/usr/local/tomcat/webapps/